sudo: false
services:
  - docker
language: python - "2.7"
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
before_install:
  - openssl aes-256-cbc -K $encrypted_ae95481c2257_key -iv $encrypted_ae95481c2257_iv
    -in wasthereannhlgamelastnight-c0aea3438a34.json.enc -out wasthereannhlgamelastnight-c0aea3438a34.json
    -d
    # Uncommenting this part would make us use greatest and latest sdk, not the cached one from travis.
    #  - rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com
    #    | bash
    #  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud version
  - gcloud auth activate-service-account --key-file wasthereannhlgamelastnight-c0aea3438a34.json
install:
  - travis_retry pip install --user pylint==1.7.5
  - travis_retry pip install --user -r src/requirements.txt
  - gcloud config set project wasthereannhlgamelastnight
  - gcloud config list
before_script:
  - pylint --version
  - pylint src/!(appengine_config).py *.py -r y
  - gcloud -q app deploy src/app.yaml --no-promote -v testing
script:
  - python e2e_test.py
deploy:
  - provider: gae
    project: wasthereannhlgamelastnight
    keyfile: wasthereannhlgamelastnight-c0aea3438a34.json
    version: master
    on: master
    no_promote: False
    config: src/app.yaml
after_deploy:
  - curl -q https://wtangy.se
  # only need the testing google appengine instance called testing while testing
  - gcloud app versions delete testing -q
#after_script:
#  # in case you want to delete testing version also while developing
#  - gcloud app versions delete testing -q
