application: wasthereannhlgamelastnight
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: wasthereannhlgamelastnight.application
