#application: wasthereannhlgamelastnight
#version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /(robots\.txt|favicon\.ico|sitemap\.xml)
  static_files: static/\1
  upload: static/.*
  secure: always

- url: /stylesheets
  static_dir: stylesheets
  secure: always

- url: /google9273e1dd86a36f05.html
  static_files: google_verification/google9273e1dd86a36f05.html
  upload: google_verification/google9273e1dd86a36f05.html
  secure: always

- url: /get_schedule
  script: get_schedule.APPLICATION
  secure: always

- url: /version
  script: version.APPLICATION
  secure: always

- url: /update_schedule
  script: update_schedule.APPLICATION
  login: admin
  secure: always

- url: /.*
  script: wasthereannhlgamelastnight.APPLICATION
  secure: always
