name: Testing WTANGY.SE

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      # TODO: Migrate to 3.10 after succesful redeploy with GitHub Actions
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
        pip install -r lint_requirements.txt
    - run: pip check
    - name: Lint with pylint
      run: |
        pylint --version
        pylint --rcfile=pylintrc src/*.py *.py
    - name: Format with black
      run: |
        black --version
        black --diff --check src/*.py *.py
    - name: Run e2e_test.py
      run: python e2e_test.py

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v3

    # https://github.com/google-github-actions/auth#with-workload-identity-federation
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: "projects/210229919199/locations/global/workloadIdentityPools/wtangy-pool/providers/my-provider"
        service_account: "wasthereannhlgamelastnight@appspot.gserviceaccount.com"
        project_id: "wasthereannhlgamelastnight"

    - name: 'Set up Cloud SDK so we can run gcloud commands'
      uses: 'google-github-actions/setup-gcloud@v1'
    - id: 'gcloud'
      name: 'gcloud'
      run: |
        gcloud config list
    - name: 'Print project id'
      run: 'echo "${{ steps.auth.outputs.project_id }}"'
    # NOTE: Not decrypting env_variables.yaml.enc only had some twitter secrets?
    - id: 'deploy_to_test'
      uses: 'google-github-actions/deploy-appengine@v1'
      project_id: wasthereannhlgamelastnight
      deliverables: src/app.yaml src/cron.yaml
      version: testing
      promote: False

    # TODO:
    #- id: 'deploy'
    #  uses: 'google-github-actions/deploy-appengine@v1'
    #  project_id: wasthereannhlgamelastnight
    #  deliverables: src/app.yaml src/cron.yaml
    #  version: master
    #  promote: True
    #  env:
    #    CLOUDSDK_APP_CLOUD_BUILD_TIMEOUT: 1800 # 30 minutes
    - name: Test that it is not completely broken 2
      run: curl -q https://wtangy.se
    - name: 'Print version_url'
      run: 'echo "${{ steps.deploy_to_test.outputs.version_url }}"'
    - name: 'Print serving_status'
      run: 'echo "${{ steps.deploy_to_test.outputs.serving_status }}"'
    # TODO: Remove testing after testing
    ## gcloud app versions delete testing -q
