name: Reusable Workflow with Google Auth and SDK setup

on:
  workflow_call:

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v3

    # https://github.com/google-github-actions/auth#with-workload-identity-federation
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: "projects/210229919199/locations/global/workloadIdentityPools/wtangy-pool/providers/my-provider"
        service_account: "wasthereannhlgamelastnight@appspot.gserviceaccount.com"
        project_id: "wasthereannhlgamelastnight"

    - name: 'Set up Cloud SDK so we can run gcloud commands'
      uses: 'google-github-actions/setup-gcloud@v1'
    - run: "gcloud config list"
    - run: 'echo "${{ steps.auth.outputs.project_id }}"'
